// V7 top-level miter: extracted puzzle netlist (gold) vs rtl_recovered/puzzle_recovered.v
// (gate, built from the six per-block V7-proven rec_* modules). Both start from an
// asserted reset; after that O and success must agree forever.
//
// Run it with `python -m tools.analysis.e2e`, which generates everything below.
// gold/gate are instantiated through "probe" wrapper modules (puzzle_probe,
// puzzle_recovered_probe, generated by tools/analysis/e2e.py) that are identical
// to the extracted netlist and rtl_recovered/puzzle_recovered.v respectively,
// except for 92 extra output ports (one per flop, `probe_fNN`) each wired,
// WITHIN THE SAME MODULE, straight from the flop's own net/reg -- gold's from its
// Q_net per rtl_recovered/blocks.json, gate's from its named reg. Ordinary ports
// are used instead of a SystemVerilog cross-module (hierarchical) reference into
// the instances below: Yosys's `flatten` pass does not reliably preserve such XMRs
// (confirmed here -- an earlier version of this miter that wrote `gold.n59` /
// `gate.bin13_msb` directly left both sides "used but no driver" after `flatten`,
// which silently turned every per-flop assert into a comparison of two disconnected
// free variables and produced a trivial, meaningless counterexample at frame 0).
// Plain output ports have no such issue.
//
// Beyond the two primary outputs, this miter asserts FLOP-LEVEL state equivalence
// for all 92 flops. This is what makes the proof tractable: since each block's own
// next-state logic was already proven equivalent in isolation (V7,
// tools.analysis.cone, one proof per rtl_recovered/<block>.v), "all 92 flops equal"
// is inductive in a single step -- equal state this cycle, plus identical
// (already-proven) combinational next-state functions, implies equal state next
// cycle -- so SymbiYosys/PDR does not have to rediscover the six per-block proofs
// or invent a deep arithmetic invariant for the mod-121 counter from scratch.
// O/success equality then follows for free (both are direct or combinational reads
// of flops already asserted equal), but both are still asserted explicitly below as
// the design's actual observable-behaviour claim.
//
// Reset is asserted during the first ("init") cycle. An async-reset flop's Q value
// before any clock edge is free/unconstrained in Yosys's formal (aig) lowering (the
// reset override only takes effect from the edge that samples RESET_B low onward),
// so checks are gated to start the cycle AFTER the init cycle: reset is asserted in
// the first cycle, and O/success/all 92 flops are required to agree from the second
// cycle on, forever after.
//
// The dfxtp "pos" flops (outgen f88-f91) have no reset pin in the gate netlist, so
// both gold and gate power up with arbitrary (in Yosys/SymbiYosys terms: free/any-
// value) initial state for those 4 bits. `ASSUME_EQUAL_NO_RESET_STATE`, when defined
// on the read_verilog -formal line (not used by tools/analysis/e2e.py), assumes the two copies'
// corresponding no-reset flops start equal; see docs/INTENT.md for why this is the
// minimal extra assumption needed and what it does and doesn't cover.
module recovered_miter (input clk, input rst_n, input enable, input I);
  wire s_gold_success, s_gate_success;
  wire [7:0] s_gold_O, s_gate_O;
  wire p_gold_f00, p_gate_f00;
  wire p_gold_f01, p_gate_f01;
  wire p_gold_f02, p_gate_f02;
  wire p_gold_f03, p_gate_f03;
  wire p_gold_f04, p_gate_f04;
  wire p_gold_f05, p_gate_f05;
  wire p_gold_f06, p_gate_f06;
  wire p_gold_f07, p_gate_f07;
  wire p_gold_f08, p_gate_f08;
  wire p_gold_f09, p_gate_f09;
  wire p_gold_f10, p_gate_f10;
  wire p_gold_f11, p_gate_f11;
  wire p_gold_f12, p_gate_f12;
  wire p_gold_f13, p_gate_f13;
  wire p_gold_f14, p_gate_f14;
  wire p_gold_f15, p_gate_f15;
  wire p_gold_f16, p_gate_f16;
  wire p_gold_f17, p_gate_f17;
  wire p_gold_f18, p_gate_f18;
  wire p_gold_f19, p_gate_f19;
  wire p_gold_f20, p_gate_f20;
  wire p_gold_f21, p_gate_f21;
  wire p_gold_f22, p_gate_f22;
  wire p_gold_f23, p_gate_f23;
  wire p_gold_f24, p_gate_f24;
  wire p_gold_f25, p_gate_f25;
  wire p_gold_f26, p_gate_f26;
  wire p_gold_f27, p_gate_f27;
  wire p_gold_f28, p_gate_f28;
  wire p_gold_f29, p_gate_f29;
  wire p_gold_f30, p_gate_f30;
  wire p_gold_f31, p_gate_f31;
  wire p_gold_f32, p_gate_f32;
  wire p_gold_f33, p_gate_f33;
  wire p_gold_f34, p_gate_f34;
  wire p_gold_f35, p_gate_f35;
  wire p_gold_f36, p_gate_f36;
  wire p_gold_f37, p_gate_f37;
  wire p_gold_f38, p_gate_f38;
  wire p_gold_f39, p_gate_f39;
  wire p_gold_f40, p_gate_f40;
  wire p_gold_f41, p_gate_f41;
  wire p_gold_f42, p_gate_f42;
  wire p_gold_f43, p_gate_f43;
  wire p_gold_f44, p_gate_f44;
  wire p_gold_f45, p_gate_f45;
  wire p_gold_f46, p_gate_f46;
  wire p_gold_f47, p_gate_f47;
  wire p_gold_f48, p_gate_f48;
  wire p_gold_f49, p_gate_f49;
  wire p_gold_f50, p_gate_f50;
  wire p_gold_f51, p_gate_f51;
  wire p_gold_f52, p_gate_f52;
  wire p_gold_f53, p_gate_f53;
  wire p_gold_f54, p_gate_f54;
  wire p_gold_f55, p_gate_f55;
  wire p_gold_f56, p_gate_f56;
  wire p_gold_f57, p_gate_f57;
  wire p_gold_f58, p_gate_f58;
  wire p_gold_f59, p_gate_f59;
  wire p_gold_f60, p_gate_f60;
  wire p_gold_f61, p_gate_f61;
  wire p_gold_f62, p_gate_f62;
  wire p_gold_f63, p_gate_f63;
  wire p_gold_f64, p_gate_f64;
  wire p_gold_f65, p_gate_f65;
  wire p_gold_f66, p_gate_f66;
  wire p_gold_f67, p_gate_f67;
  wire p_gold_f68, p_gate_f68;
  wire p_gold_f69, p_gate_f69;
  wire p_gold_f70, p_gate_f70;
  wire p_gold_f71, p_gate_f71;
  wire p_gold_f72, p_gate_f72;
  wire p_gold_f73, p_gate_f73;
  wire p_gold_f74, p_gate_f74;
  wire p_gold_f75, p_gate_f75;
  wire p_gold_f76, p_gate_f76;
  wire p_gold_f77, p_gate_f77;
  wire p_gold_f78, p_gate_f78;
  wire p_gold_f79, p_gate_f79;
  wire p_gold_f80, p_gate_f80;
  wire p_gold_f81, p_gate_f81;
  wire p_gold_f82, p_gate_f82;
  wire p_gold_f83, p_gate_f83;
  wire p_gold_f84, p_gate_f84;
  wire p_gold_f85, p_gate_f85;
  wire p_gold_f86, p_gate_f86;
  wire p_gold_f87, p_gate_f87;
  wire p_gold_f88, p_gate_f88;
  wire p_gold_f89, p_gate_f89;
  wire p_gold_f90, p_gate_f90;
  wire p_gold_f91, p_gate_f91;

  puzzle_probe gold (
      .clk(clk), .rst_n(rst_n), .enable(enable), .I(I),
      .O(s_gold_O), .success(s_gold_success),
      .probe_f00(p_gold_f00),
      .probe_f01(p_gold_f01),
      .probe_f02(p_gold_f02),
      .probe_f03(p_gold_f03),
      .probe_f04(p_gold_f04),
      .probe_f05(p_gold_f05),
      .probe_f06(p_gold_f06),
      .probe_f07(p_gold_f07),
      .probe_f08(p_gold_f08),
      .probe_f09(p_gold_f09),
      .probe_f10(p_gold_f10),
      .probe_f11(p_gold_f11),
      .probe_f12(p_gold_f12),
      .probe_f13(p_gold_f13),
      .probe_f14(p_gold_f14),
      .probe_f15(p_gold_f15),
      .probe_f16(p_gold_f16),
      .probe_f17(p_gold_f17),
      .probe_f18(p_gold_f18),
      .probe_f19(p_gold_f19),
      .probe_f20(p_gold_f20),
      .probe_f21(p_gold_f21),
      .probe_f22(p_gold_f22),
      .probe_f23(p_gold_f23),
      .probe_f24(p_gold_f24),
      .probe_f25(p_gold_f25),
      .probe_f26(p_gold_f26),
      .probe_f27(p_gold_f27),
      .probe_f28(p_gold_f28),
      .probe_f29(p_gold_f29),
      .probe_f30(p_gold_f30),
      .probe_f31(p_gold_f31),
      .probe_f32(p_gold_f32),
      .probe_f33(p_gold_f33),
      .probe_f34(p_gold_f34),
      .probe_f35(p_gold_f35),
      .probe_f36(p_gold_f36),
      .probe_f37(p_gold_f37),
      .probe_f38(p_gold_f38),
      .probe_f39(p_gold_f39),
      .probe_f40(p_gold_f40),
      .probe_f41(p_gold_f41),
      .probe_f42(p_gold_f42),
      .probe_f43(p_gold_f43),
      .probe_f44(p_gold_f44),
      .probe_f45(p_gold_f45),
      .probe_f46(p_gold_f46),
      .probe_f47(p_gold_f47),
      .probe_f48(p_gold_f48),
      .probe_f49(p_gold_f49),
      .probe_f50(p_gold_f50),
      .probe_f51(p_gold_f51),
      .probe_f52(p_gold_f52),
      .probe_f53(p_gold_f53),
      .probe_f54(p_gold_f54),
      .probe_f55(p_gold_f55),
      .probe_f56(p_gold_f56),
      .probe_f57(p_gold_f57),
      .probe_f58(p_gold_f58),
      .probe_f59(p_gold_f59),
      .probe_f60(p_gold_f60),
      .probe_f61(p_gold_f61),
      .probe_f62(p_gold_f62),
      .probe_f63(p_gold_f63),
      .probe_f64(p_gold_f64),
      .probe_f65(p_gold_f65),
      .probe_f66(p_gold_f66),
      .probe_f67(p_gold_f67),
      .probe_f68(p_gold_f68),
      .probe_f69(p_gold_f69),
      .probe_f70(p_gold_f70),
      .probe_f71(p_gold_f71),
      .probe_f72(p_gold_f72),
      .probe_f73(p_gold_f73),
      .probe_f74(p_gold_f74),
      .probe_f75(p_gold_f75),
      .probe_f76(p_gold_f76),
      .probe_f77(p_gold_f77),
      .probe_f78(p_gold_f78),
      .probe_f79(p_gold_f79),
      .probe_f80(p_gold_f80),
      .probe_f81(p_gold_f81),
      .probe_f82(p_gold_f82),
      .probe_f83(p_gold_f83),
      .probe_f84(p_gold_f84),
      .probe_f85(p_gold_f85),
      .probe_f86(p_gold_f86),
      .probe_f87(p_gold_f87),
      .probe_f88(p_gold_f88),
      .probe_f89(p_gold_f89),
      .probe_f90(p_gold_f90),
      .probe_f91(p_gold_f91)
  );
  puzzle_recovered_probe gate (
      .clk(clk), .rst_n(rst_n), .enable(enable), .I(I),
      .O(s_gate_O), .success(s_gate_success),
      .probe_f00(p_gate_f00),
      .probe_f01(p_gate_f01),
      .probe_f02(p_gate_f02),
      .probe_f03(p_gate_f03),
      .probe_f04(p_gate_f04),
      .probe_f05(p_gate_f05),
      .probe_f06(p_gate_f06),
      .probe_f07(p_gate_f07),
      .probe_f08(p_gate_f08),
      .probe_f09(p_gate_f09),
      .probe_f10(p_gate_f10),
      .probe_f11(p_gate_f11),
      .probe_f12(p_gate_f12),
      .probe_f13(p_gate_f13),
      .probe_f14(p_gate_f14),
      .probe_f15(p_gate_f15),
      .probe_f16(p_gate_f16),
      .probe_f17(p_gate_f17),
      .probe_f18(p_gate_f18),
      .probe_f19(p_gate_f19),
      .probe_f20(p_gate_f20),
      .probe_f21(p_gate_f21),
      .probe_f22(p_gate_f22),
      .probe_f23(p_gate_f23),
      .probe_f24(p_gate_f24),
      .probe_f25(p_gate_f25),
      .probe_f26(p_gate_f26),
      .probe_f27(p_gate_f27),
      .probe_f28(p_gate_f28),
      .probe_f29(p_gate_f29),
      .probe_f30(p_gate_f30),
      .probe_f31(p_gate_f31),
      .probe_f32(p_gate_f32),
      .probe_f33(p_gate_f33),
      .probe_f34(p_gate_f34),
      .probe_f35(p_gate_f35),
      .probe_f36(p_gate_f36),
      .probe_f37(p_gate_f37),
      .probe_f38(p_gate_f38),
      .probe_f39(p_gate_f39),
      .probe_f40(p_gate_f40),
      .probe_f41(p_gate_f41),
      .probe_f42(p_gate_f42),
      .probe_f43(p_gate_f43),
      .probe_f44(p_gate_f44),
      .probe_f45(p_gate_f45),
      .probe_f46(p_gate_f46),
      .probe_f47(p_gate_f47),
      .probe_f48(p_gate_f48),
      .probe_f49(p_gate_f49),
      .probe_f50(p_gate_f50),
      .probe_f51(p_gate_f51),
      .probe_f52(p_gate_f52),
      .probe_f53(p_gate_f53),
      .probe_f54(p_gate_f54),
      .probe_f55(p_gate_f55),
      .probe_f56(p_gate_f56),
      .probe_f57(p_gate_f57),
      .probe_f58(p_gate_f58),
      .probe_f59(p_gate_f59),
      .probe_f60(p_gate_f60),
      .probe_f61(p_gate_f61),
      .probe_f62(p_gate_f62),
      .probe_f63(p_gate_f63),
      .probe_f64(p_gate_f64),
      .probe_f65(p_gate_f65),
      .probe_f66(p_gate_f66),
      .probe_f67(p_gate_f67),
      .probe_f68(p_gate_f68),
      .probe_f69(p_gate_f69),
      .probe_f70(p_gate_f70),
      .probe_f71(p_gate_f71),
      .probe_f72(p_gate_f72),
      .probe_f73(p_gate_f73),
      .probe_f74(p_gate_f74),
      .probe_f75(p_gate_f75),
      .probe_f76(p_gate_f76),
      .probe_f77(p_gate_f77),
      .probe_f78(p_gate_f78),
      .probe_f79(p_gate_f79),
      .probe_f80(p_gate_f80),
      .probe_f81(p_gate_f81),
      .probe_f82(p_gate_f82),
      .probe_f83(p_gate_f83),
      .probe_f84(p_gate_f84),
      .probe_f85(p_gate_f85),
      .probe_f86(p_gate_f86),
      .probe_f87(p_gate_f87),
      .probe_f88(p_gate_f88),
      .probe_f89(p_gate_f89),
      .probe_f90(p_gate_f90),
      .probe_f91(p_gate_f91)
  );

  reg init = 1'b1;
  always @(posedge clk) init <= 1'b0;

`ifdef ASSUME_EQUAL_NO_RESET_STATE
  // The 4 outgen "pos" flops (f88-f91) have no reset; assume both copies power up
  // with the same (still arbitrary) initial value for each of them, one cycle before
  // reset is checked, so the free-running mismatch on cycle 0 doesn't block the proof.
  always @(*) begin
    if (init) begin
      assume (p_gold_f88 == p_gate_f88);
      assume (p_gold_f89 == p_gate_f89);
      assume (p_gold_f90 == p_gate_f90);
      assume (p_gold_f91 == p_gate_f91);
    end
  end
`endif

  always @(*) begin
    if (init) assume (!rst_n);
    if (!init) begin
      assert (s_gold_success == s_gate_success);
      assert (s_gold_O == s_gate_O);

      // Per-flop state equality (all 92 flops; see header comment above).
    assert (p_gold_f00 == p_gate_f00);  // f00
    assert (p_gold_f01 == p_gate_f01);  // f01
    assert (p_gold_f02 == p_gate_f02);  // f02
    assert (p_gold_f03 == p_gate_f03);  // f03
    assert (p_gold_f04 == p_gate_f04);  // f04
    assert (p_gold_f05 == p_gate_f05);  // f05
    assert (p_gold_f06 == p_gate_f06);  // f06
    assert (p_gold_f07 == p_gate_f07);  // f07
    assert (p_gold_f08 == p_gate_f08);  // f08
    assert (p_gold_f09 == p_gate_f09);  // f09
    assert (p_gold_f10 == p_gate_f10);  // f10
    assert (p_gold_f11 == p_gate_f11);  // f11
    assert (p_gold_f12 == p_gate_f12);  // f12
    assert (p_gold_f13 == p_gate_f13);  // f13
    assert (p_gold_f14 == p_gate_f14);  // f14
    assert (p_gold_f15 == p_gate_f15);  // f15
    assert (p_gold_f16 == p_gate_f16);  // f16
    assert (p_gold_f17 == p_gate_f17);  // f17
    assert (p_gold_f18 == p_gate_f18);  // f18
    assert (p_gold_f19 == p_gate_f19);  // f19
    assert (p_gold_f20 == p_gate_f20);  // f20
    assert (p_gold_f21 == p_gate_f21);  // f21
    assert (p_gold_f22 == p_gate_f22);  // f22
    assert (p_gold_f23 == p_gate_f23);  // f23
    assert (p_gold_f24 == p_gate_f24);  // f24
    assert (p_gold_f25 == p_gate_f25);  // f25
    assert (p_gold_f26 == p_gate_f26);  // f26
    assert (p_gold_f27 == p_gate_f27);  // f27
    assert (p_gold_f28 == p_gate_f28);  // f28
    assert (p_gold_f29 == p_gate_f29);  // f29
    assert (p_gold_f30 == p_gate_f30);  // f30
    assert (p_gold_f31 == p_gate_f31);  // f31
    assert (p_gold_f32 == p_gate_f32);  // f32
    assert (p_gold_f33 == p_gate_f33);  // f33
    assert (p_gold_f34 == p_gate_f34);  // f34
    assert (p_gold_f35 == p_gate_f35);  // f35
    assert (p_gold_f36 == p_gate_f36);  // f36
    assert (p_gold_f37 == p_gate_f37);  // f37
    assert (p_gold_f38 == p_gate_f38);  // f38
    assert (p_gold_f39 == p_gate_f39);  // f39
    assert (p_gold_f40 == p_gate_f40);  // f40
    assert (p_gold_f41 == p_gate_f41);  // f41
    assert (p_gold_f42 == p_gate_f42);  // f42
    assert (p_gold_f43 == p_gate_f43);  // f43
    assert (p_gold_f44 == p_gate_f44);  // f44
    assert (p_gold_f45 == p_gate_f45);  // f45
    assert (p_gold_f46 == p_gate_f46);  // f46
    assert (p_gold_f47 == p_gate_f47);  // f47
    assert (p_gold_f48 == p_gate_f48);  // f48
    assert (p_gold_f49 == p_gate_f49);  // f49
    assert (p_gold_f50 == p_gate_f50);  // f50
    assert (p_gold_f51 == p_gate_f51);  // f51
    assert (p_gold_f52 == p_gate_f52);  // f52
    assert (p_gold_f53 == p_gate_f53);  // f53
    assert (p_gold_f54 == p_gate_f54);  // f54
    assert (p_gold_f55 == p_gate_f55);  // f55
    assert (p_gold_f56 == p_gate_f56);  // f56
    assert (p_gold_f57 == p_gate_f57);  // f57
    assert (p_gold_f58 == p_gate_f58);  // f58
    assert (p_gold_f59 == p_gate_f59);  // f59
    assert (p_gold_f60 == p_gate_f60);  // f60
    assert (p_gold_f61 == p_gate_f61);  // f61
    assert (p_gold_f62 == p_gate_f62);  // f62
    assert (p_gold_f63 == p_gate_f63);  // f63
    assert (p_gold_f64 == p_gate_f64);  // f64
    assert (p_gold_f65 == p_gate_f65);  // f65
    assert (p_gold_f66 == p_gate_f66);  // f66
    assert (p_gold_f67 == p_gate_f67);  // f67
    assert (p_gold_f68 == p_gate_f68);  // f68
    assert (p_gold_f69 == p_gate_f69);  // f69
    assert (p_gold_f70 == p_gate_f70);  // f70
    assert (p_gold_f71 == p_gate_f71);  // f71
    assert (p_gold_f72 == p_gate_f72);  // f72
    assert (p_gold_f73 == p_gate_f73);  // f73
    assert (p_gold_f74 == p_gate_f74);  // f74
    assert (p_gold_f75 == p_gate_f75);  // f75
    assert (p_gold_f76 == p_gate_f76);  // f76
    assert (p_gold_f77 == p_gate_f77);  // f77
    assert (p_gold_f78 == p_gate_f78);  // f78
    assert (p_gold_f79 == p_gate_f79);  // f79
    assert (p_gold_f80 == p_gate_f80);  // f80
    assert (p_gold_f81 == p_gate_f81);  // f81
    assert (p_gold_f82 == p_gate_f82);  // f82
    assert (p_gold_f83 == p_gate_f83);  // f83
    assert (p_gold_f84 == p_gate_f84);  // f84
    assert (p_gold_f85 == p_gate_f85);  // f85
    assert (p_gold_f86 == p_gate_f86);  // f86
    assert (p_gold_f87 == p_gate_f87);  // f87
    assert (p_gold_f88 == p_gate_f88);  // f88
    assert (p_gold_f89 == p_gate_f89);  // f89
    assert (p_gold_f90 == p_gate_f90);  // f90
    assert (p_gold_f91 == p_gate_f91);  // f91
    end
  end
endmodule
